#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""gen_images.py — descarga ilustraciones a crayon (estilo coreano/japones) via Pollinations."""
import os, urllib.request, urllib.parse, io
from PIL import Image

BASE = os.path.dirname(os.path.abspath(__file__))
OUTDIR = os.path.join(BASE, "img")
os.makedirs(OUTDIR, exist_ok=True)

def fetch(name, prompt, w=1024, h=640, seed=0):
    url = ("https://image.pollinations.ai/prompt/" + urllib.parse.quote(prompt) +
           "?width=%d&height=%d&nologo=true&model=flux&seed=%d" % (w, h, seed))
    print("descargando", name, "...")
    req = urllib.request.Request(url, headers={"User-Agent": "Mozilla/5.0"})
    data = urllib.request.urlopen(req, timeout=120).read()
    im = Image.open(io.BytesIO(data)).convert("RGB")
    p = os.path.join(OUTDIR, name + ".png")
    im.save(p, "PNG")
    print("OK ->", p, im.size, len(data), "bytes")

fetch("cap01_portal", "Korean webtoon crayon illustration, dawn attack on a Yokohama port street, a tall black rectangular portal hovering upright in the asphalt releasing thick mist and monstrous dark beasts with too-long legs emerging and running, a man staring from a window, street lamps, muted teal and salmon palette, hand drawn colored crayon texture, paper grain, painterly, emotional, cinematic wide shot", seed=11)
fetch("cap01_batalla", "Korean webtoon crayon illustration, aerial battle over a ruined city at dawn, monstrous dark beasts fighting a military response, tanks firing flames and smoke, a helicopter flying low, fighter jets in the sky, artillery explosions across the street, soldiers running and firing, chaos, dramatic aerial perspective, hand drawn colored crayon texture, paper grain, muted gritty palette with orange explosion glow, painterly, cinematic", seed=23)
fetch("cap03_calle", "Korean webtoon crayon illustration, quiet lamplit street at blue hour, an old woman in a grey shawl with a red vegetable cart, a huge flat shadow creature with a head and an orange ember edge crouched on the asphalt, empty dangerous street, hand drawn colored crayon texture, paper grain, muted palette, cinematic, emotional", seed=37)
fetch("cap05_descarga", "Korean webtoon crayon illustration, night street, armored man kneeling on asphalt beside a fallen worker, round shield on the ground, faint wisps of steam and an orange glowing glove on the asphalt, dark flat shadow splitting into three pieces sliding away, street lamps, hand drawn colored crayon texture, paper grain, muted palette, tragedy, cinematic", seed=47)
fetch("cap06_cielo", "Korean webtoon crayon illustration, night coastal town at dawn, the entire sky replaced by one giant perfect silent black rectangle opening like a lid over the rooftops, faint cold light leaking at its lower edge, empty streets with lampposts in muted teal, people below frozen looking up small and alone, hand drawn colored crayon texture, paper grain, muted palette, ominous, cinematic wide shot", seed=61)
fetch("cap07_archivo", "Korean webtoon crayon illustration, dim military archive room at dawn, tall gray filing cabinets in shadow, a single wooden table with an open cardboard folder titled 13 sheets and a small photo, the warm light of one desk lamp pool on the paper, an old doctor hand reaching to close it, muted teal and amber palette, hand drawn colored crayon texture, paper grain, foreboding, cinematic", seed=73)
fetch("cap11_portal", "Korean webtoon crayon illustration, morning street in a quiet residential neighborhood, the small back patio of a kindergarten behind a low gate, a tall flat pitch-black rectangular portal standing upright against the back wall with a faint cold shimmering edge that casts no shadow, kindergarten windows glowing warm yellow from inside, a tiny child in a paint-stained smock holding a wooden stick looking at the portal, four silhouettes watching from the street fence, hand drawn colored crayon texture, paper grain, muted teal and salmon palette, ominous, emotional, cinematic wide shot", seed=83)
fetch("cap11_proteger", "Korean webtoon crayon illustration, morning kindergarten patio during a fight, a teenage boy in a bright yellow jacket with bandaged wrists spreading his arms wide as a human shield standing in front of a small child holding a wooden stick, behind him three tall pale yellow monsters with lowered heads charging through a broken gate, a round silvery shield skidding on the asphalt toward them, a red-hot crescent fan of embers sweeping across the frame, a girl in a bone-white haori and red ponytail in the background, hand drawn colored crayon texture, paper grain, muted palette with warm orange glow, drama, heroism, cinematic", seed=89)
fetch("cap13_reparto", "Korean webtoon crayon illustration, a wide abandoned railway freight yard in the morning, four figures spread far apart across an empty vast platform without a word: a tall armored man with a round industrial shield planted at the center, a small girl in a bone-white short haori with a red high ponytail and a closed ember fan at the right edge by rusty dead rails, a tall woman in a grey-blue guard uniform watching down a long scoped rifle from the street end, a young man in neon yellow with bandaged wrists standing alone in an empty gap between them, six pale yellow tall thin monsters with too-long limbs spread in formation across the yard watching them without moving, far inside a shadowed warehouse something bigger barely visible as folded darkness, hand drawn colored crayon texture, paper grain, muted teal and salmon palette, silent tension, cinematic wide shot", seed=107)
fetch("cap13_naranja", "Korean webtoon crayon illustration, inside the shadow of a big freight yard, a very tall thin dark giant with too many long arms hanging at its sides like curtains, head small and tilted, two flat empty dark eyes, standing completely still with a smoldering fan of embers glowing in its chest, quietly looking down at a small girl in a bone-white haori with a red ponytail who holds an open burning paper fan and looks back, both frozen mid-fight, a huge round shield and a scoped rifle resting on the gravel beside them, grey dust drifting, morning light through the warehouse roof, hand drawn colored crayon texture, paper grain, muted teal and amber palette, eerie, very quiet, cinematic", seed=113)
